[package]
name = "rustc_codegen_arm64"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
# tidy-alphabetical-start
object = { version = "0.39.1", default-features = false, features = ["std", "read_core", "write", "macho"] }
smallvec = "1.8.1"
tracing = "0.1"
# tidy-alphabetical-end
